# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Edge AI Implementation Memo
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The views and opinions expressed in this blog are solely personal and do not represent the positions or opinions of any affiliated organization.
baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
github_username:  RyogaYuzawa
linkedin_username: ryoga-yuzawa

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
disqus:
    shortname: my_disqus_shortname

# URL settings
url: "https://ryogayuzawa.github.io"

# Permalink structure - シンプルな構造に変更
permalink: /:title/

# Sitemap settings
sitemap:
  exclude:
    - /404.html
    - /robots.txt
    - /sitemap.xml
    - /_site/
    - /.jekyll-cache/
    - /.git/
    - /Gemfile*
    - /vendor/
  include:
    - /_posts/
    - /_pages/
    - /about/
  changefreq: weekly
  priority: 0.8
  lastmod: true

# SEO settings
keywords: "FPGA, Zynq, Vitis HLS, MIPI, AI, Embedded Systems, Xilinx"
author: "Ryoga Yuzawa"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
